CREATE DATABASE IF NOT EXISTS shop_bot;
USE shop_bot;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
telegram_id BIGINT NOT NULL,
username VARCHAR(255),
first_name VARCHAR(255)
);

CREATE TABLE products (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
description TEXT,
price DECIMAL(10,2) NOT NULL,
quantity INT DEFAULT 0
);

CREATE TABLE cart (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
product_id INT NOT NULL,
quantity INT DEFAULT 1
);

CREATE TABLE orders (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT NOT NULL,
order_items TEXT,
total DECIMAL(10,2),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
